webb_ship_fleet_create:
    pattern:  /fleet/create
    defaults: { _controller: WebbShipBundle:Fleet:create }

webb_ship_fleet_view:
    pattern:  /fleet{shortname}
    defaults: { _controller: WebbShipBundle:Fleet:show }
    requirements:
        shortname:  \d+

webb_ship_fleet_edit:
      pattern:  /fleet{shortname}/edit
      defaults: { _controller: WebbShipBundle:Fleet:edit }
      requirements:
          shortname:  \d+

#webb_ship_ship_create:
 #   pattern:  /ship/create
 #   defaults: { _controller: WebbShipBundle:Ship:create }

#webb_ship_ship_view:
 #   pattern:  /fleet{fleet}/{shortname}
 #   defaults: { _controller: WebbShipBundle:Ship:show }
 #   requirements:
 #       fleet:  \d+

#webb_ship_ship_edit:
#      pattern:  /fleet{fleet}/{shortname}/edit
#      defaults: { _controller: WebbShipBundle:Ship:edit }
#      requirements:
#          fleet:  \d+
