webb_news:
    resource: "@WebbNewsBundle/Controller/ArticleController.php"
    type: annotation

webb_page:
    resource: "@WebbPageBundle/Controller/FrontController.php"
    type: annotation

webb_post:
    resource: "@WebbPostBundle/Controller/NoteController.php"
    type: annotation

webb_ship_fleet:
    resource: "@WebbShipBundle/Resources/config/routing.yml"
    prefix:   /

webb_ship_ship:
    resource: "@WebbShipBundle/Controller/ShipController.php"
    type: annotation

webb_character:
    resource: "@WebbCharacterBundle/Controller/PersonaController.php"
    type: annotation

fos_user_profile:
    resource: "@WebbUserBundle/Controller/ProfileController.php"
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
