parameters:
#    webb_motd.example.class: Webb\MotdBundle\Example

services:
#    webb_motd.example:
#        class: %webb_motd.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]