webb_post_note_create:
    pattern:  /fleet{fleet}/{ship}/note/create
    defaults: { _controller: WebbPostBundle:Note:create, parent_id: null}

webb_post_note_reply:
    pattern:  /fleet{fleet}/{ship}/note/{parent_id}/reply
    defaults: { _controller: WebbPostBundle:Note:create}

webb_post_note_view:
    pattern:  /fleet{fleet}/{ship}/note/{id}
    defaults: { _controller: WebbPostBundle:Note:show }

webb_post_note_edit:
      pattern:  /fleet{fleet}/{ship}/note/{id}/edit
      defaults: { _controller: WebbPostBundle:Note:edit }

webb_post_note_list:
      pattern:  /fleet{fleet}/{ship}/note/list
      defaults: { _controller: WebbPostBundle:Note:list }

webb_post_note_rss:
      pattern:  /fleet{fleet}/{ship}/note/list/rss/{format}
      defaults: { _controller: WebbPostBundle:Note:feed, format: raw }
