parameters:
#    webb_post.example.class: Webb\PostBundle\Example

services:
#    webb_post.example:
#        class: %webb_post.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
