parameters:
#    webb_file.example.class: Webb\FileBundle\Example

services:
#    webb_file.example:
#        class: %webb_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
